// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_scrape_searchTerm_location_index from "./routes/api/v1/scrape/[searchTerm]/[location]/index.tsx";
import * as $api_v1_scrape_searchTerm_index from "./routes/api/v1/scrape/[searchTerm]/index.tsx";
import * as $api_v2_generate from "./routes/api/v2/generate.tsx";
import * as $api_v2_jobDetails from "./routes/api/v2/jobDetails.tsx";
import * as $api_v2_scrape from "./routes/api/v2/scrape.tsx";
import * as $cover from "./routes/cover.tsx";
import * as $index from "./routes/index.tsx";
import * as $searcher from "./routes/searcher.tsx";
import * as $cover_Cover from "./islands/cover/Cover.tsx";
import * as $cover_Form from "./islands/cover/Form.tsx";
import * as $cover_List from "./islands/cover/List.tsx";
import * as $hooks_useSearchList from "./islands/hooks/useSearchList.tsx";
import * as $searcher_Count from "./islands/searcher/Count.tsx";
import * as $searcher_Form from "./islands/searcher/Form.tsx";
import * as $searcher_Searcher from "./islands/searcher/Searcher.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/scrape/[searchTerm]/[location]/index.tsx":
      $api_v1_scrape_searchTerm_location_index,
    "./routes/api/v1/scrape/[searchTerm]/index.tsx":
      $api_v1_scrape_searchTerm_index,
    "./routes/api/v2/generate.tsx": $api_v2_generate,
    "./routes/api/v2/jobDetails.tsx": $api_v2_jobDetails,
    "./routes/api/v2/scrape.tsx": $api_v2_scrape,
    "./routes/cover.tsx": $cover,
    "./routes/index.tsx": $index,
    "./routes/searcher.tsx": $searcher,
  },
  islands: {
    "./islands/cover/Cover.tsx": $cover_Cover,
    "./islands/cover/Form.tsx": $cover_Form,
    "./islands/cover/List.tsx": $cover_List,
    "./islands/hooks/useSearchList.tsx": $hooks_useSearchList,
    "./islands/searcher/Count.tsx": $searcher_Count,
    "./islands/searcher/Form.tsx": $searcher_Form,
    "./islands/searcher/Searcher.tsx": $searcher_Searcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
