// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_scrape_searchTerm_location_index from "./routes/api/v1/scrape/[searchTerm]/[location]/index.tsx";
import * as $api_v1_scrape_searchTerm_index from "./routes/api/v1/scrape/[searchTerm]/index.tsx";
import * as $api_v2_jobDetails from "./routes/api/v2/jobDetails.tsx";
import * as $api_v2_scrape from "./routes/api/v2/scrape.tsx";
import * as $cover_index from "./routes/cover/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $searcher_index from "./routes/searcher/index.tsx";
import * as $AddToList from "./islands/AddToList.tsx";
import * as $App from "./islands/App.tsx";
import * as $Count from "./islands/Count.tsx";
import * as $Cover from "./islands/Cover.tsx";
import * as $Searcher from "./islands/Searcher.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/scrape/[searchTerm]/[location]/index.tsx":
      $api_v1_scrape_searchTerm_location_index,
    "./routes/api/v1/scrape/[searchTerm]/index.tsx":
      $api_v1_scrape_searchTerm_index,
    "./routes/api/v2/jobDetails.tsx": $api_v2_jobDetails,
    "./routes/api/v2/scrape.tsx": $api_v2_scrape,
    "./routes/cover/index.tsx": $cover_index,
    "./routes/index.tsx": $index,
    "./routes/searcher/index.tsx": $searcher_index,
  },
  islands: {
    "./islands/AddToList.tsx": $AddToList,
    "./islands/App.tsx": $App,
    "./islands/Count.tsx": $Count,
    "./islands/Cover.tsx": $Cover,
    "./islands/Searcher.tsx": $Searcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
